name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install NDK
      run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;16.1.4479499" --sdk_root=${ANDROID_SDK_ROOT}
    - name: Build with Gradle
      run: chmod +x gradlew && ./gradlew clean assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
          name: mcinabox-debug
          path: mcinabox/build/output/apk/debug/mcinabox-debug
