name: APK Release Nightly Build
on:
  workflow_dispatch:
    inputs:
      Reason:
        description: 'Reasons for temporary build'     
        required: true
        default: 'No reason.Just do it.'
  schedule:
    - cron: '0 16 * * *'
    
# 北京时间0点开始构建,环境时间也重置成北京时间了哦 PS:<del>抱歉了世界各国朋友们</del>(这里标签没用...)
# 0:00 Beijing time (zone)

jobs:
#Prepare:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Build MCinaBox APK with Gradle
#        run: |
#          chmod +x gradlew
#          ./gradlew clean :app:assembleRelease
#      - name: Upload APK
#        uses: actions/upload-artifact@v2
#        with:
#          name: app-debug
#          path: app/build/outputs/apk/debug/app-debug.apk

#  build_on_Windows:
#    name: Build on Windows
#    runs-on: windows-latest
#
#    steps:
#    - name: Setup timezone
#      uses: zcong1993/setup-timezone@master
#      with:
#        timezone: Asia/Shanghai
#
#    - name: Get current time
#      uses: srfrnk/current-time@master
#      id: current-time
#      with:
#        format: YYYY-MM-DD
#
#    - uses: actions/checkout@v2
#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1.4.3
#      with:
#        java-version: 1.8
#    - uses: actions/cache@v2
#      with:
#        path: |
#          ~/.gradle/caches
#          ~/.gradle/wrapper
#        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#        restore-keys: |
#          ${{ runner.os }}-gradle-
#    - name: Build MCinaBox Release (with gradle)
#      run: |
#          chmod +x gradlew
#          ./gradlew clean :app:assembleRelease
#      shell: bash
#    - name: Change APK name
#      run: |
#        mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/MCinaBox-${{ runner.os }}-Release-${{ steps.current-time.outputs.formattedTime }}.apk
#      shell: bash
#    - name: Upload All Pack
#      uses: actions/upload-artifact@v2
#      with:
#        name: MCinaBox-${{ runner.os }}-ReleasePack-${{ steps.current-time.outputs.formattedTime }}
#        path: app/build/outputs
#    - name: Upload APK
#      uses: actions/upload-artifact@v2
#      with:
#        name: MCinaBox-${{ runner.os }}-Release-${{ steps.current-time.outputs.formattedTime }}.apk
#        path: app/build/outputs/apk/release/MCinaBox-${{ runner.os }}-Release-${{ steps.current-time.outputs.formattedTime }}.apk

  build_on_Ubuntu:
    name: Build on Ubuntu
    runs-on: Ubuntu-latest

    steps:
    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: Asia/Shanghai
#这玩意暂时只能用在Ubuntu,正在找其他系统解决方案

    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYY-MM-DD
#暂不知道这玩意是不是取的本地时间
    
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build MCinaBox Release (with gradle)
      run: |
          chmod +x gradlew
          ./gradlew clean :app:assembleRelease
      shell: bash
    - name: Change APK name
      run: |
        mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/MCinaBox-${{ runner.os }}-Release-${{ steps.current-time.outputs.formattedTime }}.apk      
      shell: bash
    - name: Upload All Pack
      uses: actions/upload-artifact@v2
      with:
        name: MCinaBox-${{ runner.os }}-ReleasePack-${{ steps.current-time.outputs.formattedTime }}
        path: app/build/outputs
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: MCinaBox-${{ runner.os }}-Release-${{ steps.current-time.outputs.formattedTime }}.apk
        path: app/build/outputs/apk/release/MCinaBox-${{ runner.os }}-Release-${{ steps.current-time.outputs.formattedTime }}.apk

# build_on_MacOS:
#    name: Build on MacOS
#    runs-on: MacOS-latest
#
#    steps:
#    - name: Setup timezone
#      uses: zcong1993/setup-timezone@master
#      with:
#        timezone: Asia/Shanghai
#
#    - name: Get current time
#      uses: srfrnk/current-time@master
#      id: current-time
#      with:
#        format: YYYY-MM-DD
#    - uses: actions/checkout@v2
#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1.4.3
#      with:
#        java-version: 1.8
#    - uses: actions/cache@v2
#      with:
#        path: |
#          ~/.gradle/caches
#          ~/.gradle/wrapper
#        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#        restore-keys: |
#          ${{ runner.os }}-gradle-
#    - name: Build MCinaBox Release (with gradle)
#      run: |
#          chmod +x gradlew
#          ./gradlew clean :app:assembleRelease
#      shell: bash
#    - name: Change APK name
#      run: |
#        mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/MCinaBox-${{ runner.os }}-Release-${{ steps.current-time.outputs.formattedTime }}.apk
#      shell: bash
#    - name: Upload All Pack
#      uses: actions/upload-artifact@v2
#      with:
#        name: MCinaBox-${{ runner.os }}-ReleasePack-${{ steps.current-time.outputs.formattedTime }}
#        path: app/build/outputs
#    - name: Upload APK
#      uses: actions/upload-artifact@v2
#      with:
#        name: MCinaBox-${{ runner.os }}-Release-${{ steps.current-time.outputs.formattedTime }}.apk
#        path: app/build/outputs/apk/release/MCinaBox-${{ runner.os }}-Release-${{ steps.current-time.outputs.formattedTime }}.apk
