# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build_on_Windows:
      name: Build on Windows
      runs-on: windows-latest

      steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
      
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build MCinaBox Release (with gradle)
        run: |
            chmod +x gradlew
            ./gradlew clean :app:assembleRelease
        shell: bash
      - name: Change APK name
        run: |
          export BUILDDATE=$(date +%F)
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/MCinaBox-${{ runner.os }}-Release-${{BUILDDATE}}.apk
        shell: bash
      - name: Upload All Pack
        uses: actions/upload-artifact@v2
        with:
          name: MCinaBox-${{ runner.os }}-ReleasePack-${{BUILDDATE}}
          path: app/build/outputs
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: MCinaBox-${{ runner.os }}-Release-${{BUILDDATE}}.apk
          path: app/build/outputs/apk/release/MCinaBox-${{ runner.os }}-Release-${{BUILDDATE}}.apk
